## Dizi
- sayi_dizi = 1,2,3,4,5
- sayi_dizi = 2.3,0.34,0.56
- karakter_dizisi ="Merhaba Dünya!!!"
- karakter_dizisi = "A","b","G",'c','d'

## Liste

- meyve_listesi=["Elma","Armut,"Çilek"] #string listesi
- liste = [1,2,3,4.5,"dünya",["Elma","Armut,"Çilek"]]

In [1]:
liste = [1,2,3,4.5,"dünya",["Elma","Armut","Çilek"]]

In [2]:
print(liste)

[1, 2, 3, 4.5, 'dünya', ['Elma', 'Armut', 'Çilek']]


In [3]:
print(liste[4][2])

n


In [4]:
type(liste[5])

list

In [5]:
print(liste[3:5])

[4.5, 'dünya']


## Listeye Eleman Ekleme

- append  listenin sonuna eleman ekleme
- insert  liste belirli indisine elemena ekleme için kulllanılır

In [6]:
liste = [1,3,4,5,6,7,8,9]
print(liste)

[1, 3, 4, 5, 6, 7, 8, 9]


In [7]:
liste.append(10)
print(liste)

[1, 3, 4, 5, 6, 7, 8, 9, 10]


In [8]:
liste.insert(1,2)
print(liste)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [10]:
print(len(liste))

10


In [11]:
print(liste.count(8))

1


In [12]:
liste1 = [1,3,4,5,6,7,8,9]
liste2 = ["a","b","c","d","d","c","c","d"]

### Python dilinde koleksiyonlar
list(liste), tupple(demet), dictionary (sözlük), set(küme)

mutable: list(liste),dictionary (sözlük),set(küme)
inmutable: tupple(demet)

In [13]:
print(liste1)
liste1.extend(liste2)
print(liste1)

[1, 3, 4, 5, 6, 7, 8, 9]
[1, 3, 4, 5, 6, 7, 8, 9, 'a', 'b', 'c', 'd', 'd', 'c', 'c', 'd']


In [14]:
print(liste1)

[1, 3, 4, 5, 6, 7, 8, 9, 'a', 'b', 'c', 'd', 'd', 'c', 'c', 'd']


In [15]:
print(liste1.count('d'))

3


In [16]:
print(liste2)

['a', 'b', 'c', 'd', 'd', 'c', 'c', 'd']


In [17]:
liste2 = liste2 + liste1
print(liste2)

['a', 'b', 'c', 'd', 'd', 'c', 'c', 'd', 1, 3, 4, 5, 6, 7, 8, 9, 'a', 'b', 'c', 'd', 'd', 'c', 'c', 'd']


In [18]:
liste1 = [1,3,4,5,6,7,8,9]
print(liste1)

[1, 3, 4, 5, 6, 7, 8, 9]


In [19]:
liste1.reverse()
print(liste1)

[9, 8, 7, 6, 5, 4, 3, 1]


In [20]:
bos_liste = []

In [21]:
print(bos_liste)

[]


# for döngüsü

bir işlemin kaç kere yapıldığını bildiğimiz döngü türüdür

In [22]:
liste1 = [1,3,4,5,6,7,8,9]
for i in liste1:
    print(i)

1
3
4
5
6
7
8
9


In [24]:
meyveler = ["Elma","Armut","Muz","Ananas","Çilek"]
for i in range(len(meyveler)):        #range(ilk,son,adım) 0,1,2,3,4
    print(f"{i+1}. meyve: {meyveler[i]}")

1. meyve: Elma
2. meyve: Armut
3. meyve: Muz
4. meyve: Ananas
5. meyve: Çilek


In [25]:
meyveler = ["Elma","Armut","Muz","Ananas","Çilek"]
i = 0
for meyve in meyveler:
    i = i + 1
    print(f"{i}. meyve: {meyve}")

1. meyve: Elma
2. meyve: Armut
3. meyve: Muz
4. meyve: Ananas
5. meyve: Çilek


# Veri Bilimi Paketler, Kütüphane

## Numpy 
numeric python

- skaler (tek sayı) 7
- vektör (dizi) [3,6,7]
- matris (2D) 2 3 5
              5 6 7
              7 9 10
- tensor (nD) 

## Pandas
excel, DataFrame, Seriler

## matplotlib 
veri görselleştirme kütüphanesi

## Seaborn, plotly 

## scikitlearn 

## Tensorflow ve Keras

## Open CV 

## Scikit-image, Pillow

In [26]:
import numpy as np

In [28]:
dizi = np.arange(6)

In [29]:
print(dizi)

[0 1 2 3 4 5]


In [30]:
type(dizi)

numpy.ndarray

In [35]:
from numpy import arange,reshape

In [36]:
a= arange(15)

In [37]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [38]:
b = a.reshape(3,5) 

In [39]:
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [41]:
while True:
    heartRate = input("Hastanın dakikadaki Kalp hızı  ")
    try:
        heartRate = int(heartRate)
    except:
        print("Sayısal bir değer girmediniz")
        continue
    else:
        break

Hastanın dakikadaki Kalp hızı  eee
Sayısal bir değer girmediniz
Hastanın dakikadaki Kalp hızı  44.5
Sayısal bir değer girmediniz
Hastanın dakikadaki Kalp hızı  33


In [50]:
def sayisal_input(metin,tipi):
    """metin ekrana yazılacak bilgi , tipi integer , float"""
    while True:
        deger = input(metin)
        try:
            if tipi == "int":
                deger = int(deger)
            elif tipi =="float":
                deger = float(deger)
            else:
                tipi = input("Veri tipiniz (int)eger veya (float) türünde olmalı")
                raise ValueError("")
        except ValueError:
            print("Sayısal bir değer girmediniz")
            continue
        else:
            return deger

In [51]:
heartRate = sayisal_input("Hastanın dakikadaki Kalp hızı  ","ee")

Hastanın dakikadaki Kalp hızı  22
Veri tipiniz (int)eger veya (float) türünde olmalıint
Sayısal bir değer girmediniz
Hastanın dakikadaki Kalp hızı  22


In [52]:
print(heartRate)

22


In [53]:
help(sayisal_input)

Help on function sayisal_input in module __main__:

sayisal_input(metin, tipi)
    metin ekrana yazılacak bilgi , tipi integer , float



In [54]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [ ]:
murat.gezer@gmail.com